[
  {
    "slug": "988-lifeline",
    "name": "988 Suicide & Crisis Lifeline",
    "category": "crisis",
    "description": "Free, confidential 24/7 crisis support by call, text, or chat for anyone in suicidal crisis or emotional distress.",
    "phone": "988",
    "address": "",
    "area": "National",
    "hours": "24/7",
    "hours247": true,
    "free": true,
    "requirements": "None. Call or text 988 from anywhere in the US.",
    "website": "https://988lifeline.org"
  },
  {
    "slug": "samhsa-helpline",
    "name": "SAMHSA National Helpline",
    "category": "crisis",
    "description": "Free, confidential 24/7 treatment referral and information service for mental health and/or substance use disorders, in English and Spanish.",
    "phone": "1-800-662-4357",
    "address": "",
    "area": "National",
    "hours": "24/7, 365 days",
    "hours247": true,
    "free": true,
    "requirements": "None.",
    "website": "https://www.samhsa.gov/find-help/helplines/national-helpline"
  },
  {
    "slug": "211-texas",
    "name": "211 Texas",
    "category": "start-here",
    "description": "Connects Texans to local health and human services of every kind — the best starting point when you don't know where else to look.",
    "phone": "211",
    "address": "",
    "area": "Texas (statewide)",
    "hours": "24/7",
    "hours247": true,
    "free": true,
    "requirements": "None. Dial 211 or use 211texas.org.",
    "website": "https://www.211texas.org"
  },
  {
    "slug": "genesis-womens-shelter",
    "name": "Genesis Women's Shelter & Support",
    "category": "domestic-violence",
    "description": "24-hour helpline, emergency shelter, long-term housing, advocacy, counseling, and legal services for women affected by domestic violence.",
    "phone": "214-946-4357",
    "address": "",
    "area": "Dallas, TX",
    "hours": "24/7 helpline",
    "hours247": true,
    "free": true,
    "requirements": "None to call the helpline. Shelter location is confidential for resident safety.",
    "website": "https://www.genesisshelter.org"
  },
  {
    "slug": "homeward-bound",
    "name": "Homeward Bound, Inc.",
    "category": "recovery",
    "description": "Detox, residential treatment, outpatient services, and medication-assisted treatment (MAT) for substance use disorders.",
    "phone": "214-941-3500",
    "address": "5300 University Hills Blvd, Dallas, TX 75241",
    "area": "Dallas, TX",
    "hours": "Lobby hours Mon-Fri 8am-4:30pm; first-come, first-served",
    "hours247": false,
    "free": false,
    "requirements": "Accepts Medicaid, Blue Cross Blue Shield, Molina Healthcare, and uninsured patients.",
    "website": "https://www.homewardboundinc.org",
    "offersDetox": true
  },
  {
    "slug": "salvation-army-carr-p-collins",
    "name": "Salvation Army — Carr P. Collins Social Service Center",
    "category": "shelter",
    "description": "Men's and women's shelter, substance abuse program, food pantry, meals, and life-skills classes.",
    "phone": "214-424-7000",
    "address": "5302 Harry Hines Blvd, Dallas, TX 75235",
    "area": "Dallas, TX",
    "hours": "Call for current intake hours",
    "hours247": false,
    "free": true,
    "requirements": "Call ahead to confirm current intake process and availability.",
    "website": "https://salvationarmyntx.org"
  },
  {
    "slug": "salvation-army-mabee",
    "name": "Salvation Army — Mabee Social Service Center",
    "category": "shelter",
    "description": "Emergency family homeless shelter, daily meals for the homeless, and transitional programs.",
    "phone": "817-344-1800",
    "address": "1855 E Lancaster Ave, Fort Worth, TX 76103",
    "area": "Fort Worth, TX",
    "hours": "Call for current intake hours",
    "hours247": false,
    "free": true,
    "requirements": "Call ahead to confirm current intake process and availability.",
    "website": "https://salvationarmyntx.org"
  },
  {
    "slug": "salvation-army-arlington",
    "name": "Salvation Army — Arlington Family Life Shelter",
    "category": "shelter",
    "description": "Family shelter with stays up to 14 weeks, job placement skills, and a supportive housing program.",
    "phone": "817-860-1836",
    "address": "712 W Abram St, Arlington, TX 76013",
    "area": "Arlington, TX",
    "hours": "Call for current intake hours",
    "hours247": false,
    "free": true,
    "requirements": "Call ahead to confirm current intake process and availability.",
    "website": "https://salvationarmyntx.org"
  },
  {
    "slug": "salvation-army-denton",
    "name": "Salvation Army — Denton Shelter",
    "category": "shelter",
    "description": "Emergency night shelter, food pantry, KARE Kitchen community meal, and a social service center.",
    "phone": "940-566-3800",
    "address": "1508 E McKinney St, Denton, TX 76209",
    "area": "Denton, TX",
    "hours": "Call for current intake hours",
    "hours247": false,
    "free": true,
    "requirements": "Call ahead to confirm current intake process and availability.",
    "website": "https://salvationarmyntx.org"
  },
  {
    "slug": "resource-center-dallas",
    "name": "Resource Center Dallas",
    "category": "lgbtq",
    "description": "Mental healthcare, support groups, HIV/STI testing, PrEP care, and hormone therapy services for the LGBTQIA+ community.",
    "phone": "214-521-5124",
    "address": "5750 Cedar Springs Rd, Dallas, TX 75235",
    "area": "Dallas, TX",
    "hours": "Mon-Fri 9am-5pm",
    "hours247": false,
    "free": false,
    "requirements": "Call to schedule; some services are free or sliding-scale.",
    "website": "https://myresourcecenter.org"
  },
  {
    "slug": "help-center-fw",
    "name": "HELP Center for LGBTQ+ Health",
    "category": "lgbtq",
    "description": "Free HIV/STI testing and prevention, PrEP/PEP telehealth, and counseling regardless of income or insurance status.",
    "phone": "817-332-7722",
    "address": "1919 8th Ave, Fort Worth, TX 76110",
    "area": "Fort Worth, TX",
    "hours": "Call for current hours",
    "hours247": false,
    "free": true,
    "requirements": "None — services provided regardless of income or insurance status.",
    "website": "https://helpcentertx.org"
  },
  {
    "slug": "help-center-arlington",
    "name": "HELP Center for LGBTQ+ Health — Arlington Clinic",
    "category": "lgbtq",
    "description": "Free HIV/STI testing and prevention, PrEP/PEP telehealth, and counseling regardless of income or insurance status. Arlington location of HELP Center for LGBTQ+ Health.",
    "phone": "817-200-6500",
    "address": "602 E South Street, Arlington, TX 76010",
    "area": "Arlington, TX",
    "hours": "Mon-Fri 9am-5pm",
    "hours247": false,
    "free": true,
    "requirements": "None — services provided regardless of income or insurance status.",
    "website": "https://helpcentertx.org"
  },
  {
    "slug": "ntfb",
    "name": "North Texas Food Bank",
    "category": "food",
    "description": "Food pantry locator and SNAP application assistance for North Texas households.",
    "phone": "214-330-1396",
    "address": "3677 Mapleshade Ln, Plano, TX 75075",
    "area": "North Texas (multi-county)",
    "hours": "Mon-Fri 8:30am-4:30pm, Sat 8:30am-3:30pm",
    "hours247": false,
    "free": true,
    "requirements": "Use the pantry locator to find your nearest partner pantry; call ahead to confirm hours.",
    "website": "https://ntfb.org"
  },
  {
    "slug": "tafb",
    "name": "Tarrant Area Food Bank",
    "category": "food",
    "description": "Food pantry locator, SNAP assistance, and senior box program for Tarrant County.",
    "phone": "817-857-7100",
    "address": "2600 Cullen St, Fort Worth, TX 76107",
    "area": "Tarrant County, TX",
    "hours": "Call for current hours",
    "hours247": false,
    "free": true,
    "requirements": "Use the pantry locator to find your nearest partner pantry; call ahead to confirm hours.",
    "website": "https://tafb.org"
  },
  {
    "slug": "minnies-food-pantry",
    "name": "Minnie's Food Pantry",
    "category": "food",
    "description": "Drive-thru food pantry — no income test, no interview. Homeless individuals may visit weekly on foot.",
    "phone": "972-596-0253",
    "address": "661 18th St, Plano, TX 75074",
    "area": "Plano, TX",
    "hours": "Wed-Sat 8:30am-11:30am (closed every 5th Saturday)",
    "hours247": false,
    "free": true,
    "requirements": "Bring a photo ID and a utility bill. Households may visit once a month via drive-thru; homeless individuals may visit weekly on foot.",
    "website": "https://minniesfoodpantry.org"
  },
  {
    "slug": "mission-arlington",
    "name": "Mission Arlington",
    "category": "food",
    "description": "Emergency food assistance and a wide range of family support services, six days a week.",
    "phone": "817-277-6620",
    "address": "210 W South St, Arlington, TX 76010",
    "area": "Arlington, TX",
    "hours": "Mon-Sat 7am-7pm (drop-off); emergency assistance Mon-Fri 8am-5pm, Sat 9am-2pm",
    "hours247": false,
    "free": true,
    "requirements": "No income test stated. Families receive 3-5 days of food based on family size.",
    "website": "https://missionarlington.org"
  },
  {
    "slug": "metrocrest-services",
    "name": "Metrocrest Services",
    "category": "food",
    "description": "Choice food pantry serving Carrollton, Addison, Farmers Branch, Coppell, and part of Dallas.",
    "phone": "972-446-2100",
    "address": "1145 N Josey Ln, Carrollton, TX 75006",
    "area": "Carrollton, TX",
    "hours": "Mon-Fri 8:30am-3pm, Sat 9am-1pm",
    "hours247": false,
    "free": true,
    "requirements": "Appointment required. No proof needed if already on SNAP/TANF/SSI or income under federal poverty guidelines; homelessness and disaster survivors auto-qualify. Provides ~14 days of food per visit.",
    "website": "https://metrocrestservices.org"
  },
  {
    "slug": "mckinney-food-pantry",
    "name": "Community Food Pantry of McKinney",
    "category": "food",
    "description": "Choice pantry where families shop for their own groceries in a welcoming space.",
    "phone": "972-547-4404",
    "address": "307 Smith St, McKinney, TX 75069",
    "area": "McKinney, TX",
    "hours": "Mon-Wed 11am-3:30pm, Thu 11am-6:30pm, Fri 10am-12:30pm",
    "hours247": false,
    "free": true,
    "requirements": "Address and family size info; income eligibility per North Texas Food Bank guidelines; must reside in McKinney or surrounding area. Weekly visits allowed.",
    "website": "https://www.mckinneyfoodpantry.org"
  },
  {
    "slug": "denton-community-food-center",
    "name": "Denton Community Food Center",
    "category": "food",
    "description": "Appointment-based pantry where clients individually select their own items with volunteer help.",
    "phone": "940-382-0807",
    "address": "306 N Loop 288, Denton, TX 76209",
    "area": "Denton, TX",
    "hours": "Mon 10:30am-12:15pm; Wed 10:30am-12:15pm (appointment only)",
    "hours247": false,
    "free": true,
    "requirements": "Appointment required (register at app.pantrysoft.com/login/denton). Valid ID (passport, SNAP card, or green card OK) and proof of address in Denton or northern Denton County. Once a month, up to 12 visits per year.",
    "website": "https://www.dentoncfc.org"
  },
  {
    "slug": "citysquare-food-pantry",
    "name": "CitySquare Opportunity Center Food Pantry",
    "category": "food",
    "description": "Walk-up food pantry with a number-based queue system, plus benefits assistance.",
    "phone": "214-823-8710",
    "address": "1610 S Malcolm X Blvd, Dallas, TX 75226",
    "area": "Dallas, TX",
    "hours": "Tue-Fri 9am-3pm (closed noon-1pm for restocking)",
    "hours247": false,
    "free": true,
    "requirements": "Bring a photo ID. Walk up and wait for your number to be called.",
    "website": "https://www.citysquare.org"
  },
  {
    "slug": "union-gospel-mission-tarrant",
    "name": "Union Gospel Mission of Tarrant County",
    "category": "clothing",
    "description": "Clothing, hygiene items, bedding, and household essentials for people in need.",
    "phone": "817-339-2553",
    "address": "1321 E Lancaster Ave, Fort Worth, TX 76102",
    "area": "Fort Worth, TX",
    "hours": "Mon-Fri 9am-4pm",
    "hours247": false,
    "free": true,
    "requirements": "Call ahead to confirm current distribution process.",
    "website": "https://ugm-tc.org"
  },
  {
    "slug": "recovery-resource-council",
    "name": "Recovery Resource Council",
    "category": "recovery",
    "description": "Nonprofit providing free substance use screenings and referrals (OSAR), an outpatient treatment program, peer recovery support, and an overdose response/Narcan team.",
    "phone": "817-332-6329",
    "address": "157 Blandin St, Fort Worth, TX 76111",
    "area": "Fort Worth, TX",
    "hours": "Mon-Fri 8am-5pm (some services by appointment)",
    "hours247": false,
    "free": true,
    "requirements": "Call to schedule; free screening and referral, no insurance required for intake/OSAR services.",
    "website": "https://recoverycouncil.org"
  },
  {
    "slug": "cenikor-foundation",
    "name": "Cenikor Foundation",
    "category": "recovery",
    "description": "Nonprofit addiction treatment provider offering detox, inpatient residential, outpatient, day treatment (PHP), and medication-assisted treatment.",
    "phone": "1-888-236-4567",
    "address": "2425 Texas Dr, Irving, TX 75062",
    "area": "Irving, TX",
    "hours": "24/7 helpline",
    "hours247": true,
    "free": true,
    "requirements": "Call the 24/7 helpline for assessment; Medicaid, private insurance, self-pay, or financial assistance accepted.",
    "website": "https://www.cenikor.org",
    "offersDetox": true
  },
  {
    "slug": "ntace",
    "name": "North Texas Addiction Counseling & Education (NTACE)",
    "category": "recovery",
    "description": "Nonprofit outpatient center offering medication for opioid use disorder, standard/intensive outpatient counseling, women's sober living, and peer recovery support.",
    "phone": "817-795-8278",
    "address": "124 W Pioneer Parkway, Suite 170, Arlington, TX 76010",
    "area": "Arlington, TX",
    "hours": "Mon-Fri; 24-hour access line also available at 817-723-3984",
    "hours247": true,
    "free": true,
    "requirements": "Comprehensive intake and assessment required; Medicaid, major insurance, and state-funded/uninsured pathways available.",
    "website": "https://ntace.org"
  },
  {
    "slug": "addicare-group-of-texas",
    "name": "Addicare Group of Texas",
    "category": "recovery",
    "description": "Nonprofit outpatient center offering substance abuse and dependency counseling, DWI/drug offender education, and relapse prevention services.",
    "phone": "972-278-4760",
    "address": "2722 W Kingsley Rd, Suite 115, Garland, TX 75041",
    "area": "Garland, TX",
    "hours": "Mon-Thu 8:30am-8pm, Fri 8am-12pm",
    "hours247": false,
    "free": false,
    "requirements": "Call to enroll; online pay option available. Cost/sliding-scale details aren't published on their site — call to confirm before assuming free services.",
    "website": "https://addicare.com"
  },
  {
    "slug": "grace-to-change",
    "name": "Grace To Change",
    "category": "recovery",
    "description": "Outpatient substance use treatment center offering an Intensive Outpatient Program, a Supportive Outpatient Program, and individual counseling.",
    "phone": "972-542-2900",
    "address": "1216 North Central Expressway, Suite 104, McKinney, TX 75070",
    "area": "McKinney, TX",
    "hours": "Call for current hours (individual counseling weekdays; group sessions weekday evenings)",
    "hours247": false,
    "free": false,
    "requirements": "Call to schedule an intake assessment; contact office directly for insurance/payment details.",
    "website": "https://gracetochange.org"
  },
  {
    "slug": "metrocare-services",
    "name": "Metrocare Services",
    "category": "crisis",
    "description": "Dallas County's local mental health authority, providing outpatient clinics, crisis services, and support programs for adults and children.",
    "phone": "214-743-1200",
    "address": "3242 Remond Drive, Dallas, TX 75211",
    "area": "Dallas, TX",
    "hours": "Mon-Fri 8am-5pm (offices); 24/7 crisis line at 866-260-8000",
    "hours247": true,
    "free": true,
    "requirements": "Appointments generally preferred for outpatient intake; call the crisis line for immediate emergencies.",
    "website": "https://www.metrocareservices.org"
  },
  {
    "slug": "mhmr-tarrant",
    "name": "My Health My Resources (MHMR) of Tarrant County",
    "category": "crisis",
    "description": "Tarrant County's local mental health authority, providing mental health, substance-use, and IDD services plus a 24/7 crisis call center and mobile crisis outreach team.",
    "phone": "817-335-3022",
    "address": "300 Pennsylvania Ave, Fort Worth, TX 76104",
    "area": "Fort Worth, TX",
    "hours": "Clinic hours vary by center; ICARE crisis line (1-800-866-2465) is 24/7",
    "hours247": true,
    "free": false,
    "requirements": "Call ahead for intake scheduling; crisis line available anytime with no appointment needed.",
    "website": "https://mhmrtarrant.org"
  },
  {
    "slug": "lifepath-systems",
    "name": "LifePath Systems",
    "category": "crisis",
    "description": "Collin County's local mental health authority, offering crisis services, adult and youth/family mental health programs, and IDD services.",
    "phone": "972-562-0190",
    "address": "2295 Bloomdale Road, McKinney, TX 75069",
    "area": "McKinney, TX",
    "hours": "Clinic hours vary; 24/7 crisis line at 1-877-422-5939",
    "hours247": true,
    "free": false,
    "requirements": "Call the crisis line anytime; contact clinics to schedule outpatient intake.",
    "website": "https://www.lifepathsystems.org"
  },
  {
    "slug": "denton-county-mhmr",
    "name": "Denton County MHMR Center",
    "category": "crisis",
    "description": "Denton County's local mental health authority, providing mental health services, IDD support, substance-use treatment, and 24/7 crisis intervention.",
    "phone": "940-381-5000",
    "address": "2519 Scripture St, Denton, TX 76201",
    "area": "Denton, TX",
    "hours": "Mon-Fri 8am-5pm (offices); crisis services 24/7 via 1-800-762-0157 or 988",
    "hours247": true,
    "free": true,
    "requirements": "None for crisis line; sliding fee scale application for ongoing services, Medicaid accepted.",
    "website": "https://www.dentonmhmr.org"
  },
  {
    "slug": "millwood-hospital",
    "name": "Millwood Hospital",
    "category": "crisis",
    "description": "Private behavioral health hospital offering inpatient and outpatient psychiatric and substance-use treatment for children through senior adults, with 24/7 crisis assessment.",
    "phone": "817-261-3121",
    "address": "1011 North Cooper Street, Arlington, TX 76011",
    "area": "Arlington, TX",
    "hours": "Open 24 hours/7 days a week for crisis assessment",
    "hours247": true,
    "free": false,
    "requirements": "Call ahead or walk in for a psychiatric assessment; insurance/Medicaid verification as part of intake.",
    "website": "https://millwoodhospital.com",
    "offersDetox": true
  },
  {
    "slug": "now-forward-clothes-closet",
    "name": "Now-Forward — Clothes Closet",
    "category": "clothing",
    "description": "Free clothing, shoes, and accessories for adults and children in need, part of a broader emergency-assistance nonprofit.",
    "phone": "214-358-8700",
    "address": "2875 Merrell Road, Dallas, TX 75229",
    "area": "Dallas, TX",
    "hours": "Mon, Tue, Thu, Fri 12:30pm-3:30pm; Wed 10:30am-12:30pm",
    "hours247": false,
    "free": true,
    "requirements": "Must reside in Dallas County or zip codes 75023/75074/75075; register at first visit with photo ID, Medicaid card, or birth certificate; must be 18+.",
    "website": "https://now-forward.org"
  },
  {
    "slug": "cwjc-arlington-career-closet",
    "name": "Christian Women's Job Corps of Greater Arlington — Career Closet",
    "category": "clothing",
    "description": "Provides free professional interview and work attire to women enrolled in its job-readiness program.",
    "phone": "817-275-5600",
    "address": "1417 West Arkansas Lane, Suite 100, Arlington, TX 76013",
    "area": "Arlington, TX",
    "hours": "Mon-Thu 9am-3pm",
    "hours247": false,
    "free": true,
    "requirements": "Limited to women enrolled in the CWJC program, not general walk-in public.",
    "website": "https://cwjcarlington.org"
  },
  {
    "slug": "northgate-umc-clothes-closet",
    "name": "Northgate United Methodist Church — Food Pantry & Clothes Closet",
    "category": "clothing",
    "description": "Church-run clothes closet operating alongside a food pantry, offering free clothing to community members.",
    "phone": "972-252-8519",
    "address": "3700 West Northgate Drive, Irving, TX 75062",
    "area": "Irving, TX",
    "hours": "1st and 3rd Saturdays of the month, 8:30am-10:30am",
    "hours247": false,
    "free": true,
    "requirements": "None — no appointment necessary.",
    "website": "https://www.northgateumc.org"
  },
  {
    "slug": "the-roc-clothes-closet",
    "name": "The ROC (Metro Family Ministries) — Clothes Closet & Food Pantry",
    "category": "clothing",
    "description": "Community outreach ministry offering gently used clothing for kids and adults alongside its food pantry.",
    "phone": "972-272-1002",
    "address": "3375 Edgewood Dr, Garland, TX 75042",
    "area": "Garland, TX",
    "hours": "Every 3rd Saturday of the month, 9am-1pm",
    "hours247": false,
    "free": true,
    "requirements": "None — no appointment needed.",
    "website": "https://www.rocgarland.org"
  },
  {
    "slug": "sharing-life-clothing",
    "name": "Sharing Life Community Outreach — Non-Food Essentials",
    "category": "clothing",
    "description": "Accredited nonprofit providing free clothing, shoes, hygiene products, and other essentials alongside its food pantry.",
    "phone": "972-285-5819",
    "address": "3795 W Emporium Circle, Mesquite, TX 75150",
    "area": "Mesquite, TX",
    "hours": "Available during food pantry hours — call for current schedule",
    "hours247": false,
    "free": true,
    "requirements": "None for clothing; a separate durable-medical-equipment program requires documented financial/medical need.",
    "website": "https://sharing.life"
  },
  {
    "slug": "heart-of-the-city-lewisville-clothing",
    "name": "Heart of the City Lewisville — GRAHAMS Free Clothes",
    "category": "clothing",
    "description": "Nonprofit clothing-assistance program distributing free clothing to neighbors in need, by appointment or online request.",
    "phone": "972-824-6171",
    "address": "2021 N Mill St, Lewisville, TX 75057",
    "area": "Lewisville, TX",
    "hours": "Office hours Mon-Thu 9am-3pm — call for current clothing-distribution hours",
    "hours247": false,
    "free": true,
    "requirements": "None required for the clothing program itself.",
    "website": "https://heartofthecitylewisville.com"
  },
  {
    "slug": "the-archway-tarrant",
    "name": "The Archway (formerly SafeHaven of Tarrant County)",
    "category": "domestic-violence",
    "description": "24/7 crisis support, emergency shelter/housing, legal services, and children's programs for domestic violence survivors in Tarrant County.",
    "phone": "1-877-701-7233",
    "address": "1010 N Center St, Arlington, TX 76011",
    "area": "Arlington, TX",
    "hours": "Admin office Mon-Fri 9am-4pm; 24/7 crisis hotline",
    "hours247": true,
    "free": true,
    "requirements": "None — call the hotline first for shelter intake. Shelter location is confidential for resident safety.",
    "website": "https://www.thearchwaytx.org"
  },
  {
    "slug": "one-safe-place",
    "name": "One Safe Place (Tarrant County Family Justice Center)",
    "category": "domestic-violence",
    "description": "Multi-agency family justice center where 25+ partner agencies provide domestic violence advocacy, legal assistance, counseling, and children's services under one roof, at no cost.",
    "phone": "817-916-4323",
    "address": "1100 Hemphill St, Fort Worth, TX 76104",
    "area": "Fort Worth, TX",
    "hours": "Mon-Fri 8am-5pm; no appointment needed",
    "hours247": false,
    "free": true,
    "requirements": "None — walk in or call ahead.",
    "website": "https://onesafeplace.org"
  },
  {
    "slug": "denton-county-friends-of-the-family",
    "name": "Denton County Friends of the Family",
    "category": "domestic-violence",
    "description": "Full-service domestic violence and sexual assault agency offering emergency shelter, transitional housing, legal advocacy, counseling, and a 24-hour crisis line.",
    "phone": "940-382-7273",
    "address": "4845 South Interstate 35E, Suite 200, Corinth, TX 76210",
    "area": "Corinth, TX",
    "hours": "Outreach office Mon-Thu 8:30am-8pm, Fri 8:30am-5pm, Sat 10am-2pm; crisis line 24/7",
    "hours247": true,
    "free": true,
    "requirements": "All intakes go through the crisis line or outreach office. Emergency shelter location is confidential.",
    "website": "https://dcfof.org"
  },
  {
    "slug": "hopes-door-new-beginning-center",
    "name": "Hope's Door New Beginning Center",
    "category": "domestic-violence",
    "description": "Free, confidential emergency shelter, counseling, legal support, and advocacy for domestic violence survivors and their children across Collin County.",
    "phone": "972-276-0057",
    "address": "218 N 10th Street, Garland, TX 75040",
    "area": "Garland, TX",
    "hours": "Garland office Mon-Fri 9am-5pm; hotline 24/7",
    "hours247": true,
    "free": true,
    "requirements": "None — serves anyone impacted by domestic abuse regardless of gender or immigration status. Shelter locations are confidential.",
    "website": "https://hdnbc.org"
  },
  {
    "slug": "peace-in-the-home-tmwf",
    "name": "Peace in the Home Family Services (Texas Muslim Women's Foundation)",
    "category": "domestic-violence",
    "description": "Confidential emergency shelter (Peaceful Oasis), 24/7 hotline, transitional housing, legal support, and trauma-informed counseling across 20 North Texas counties.",
    "phone": "469-467-6241",
    "address": "",
    "area": "Plano, TX",
    "hours": "Call for current hours; hotline is 24/7",
    "hours247": true,
    "free": true,
    "requirements": "None specified — open to all regardless of background. Shelter location is confidential.",
    "website": "https://tmwf.org"
  },
  {
    "slug": "irving-family-advocacy-center",
    "name": "Irving Family Advocacy Center (IFAC)",
    "category": "domestic-violence",
    "description": "City-affiliated legal/victim advocacy center offering crisis counseling, protective-order assistance, court accompaniment, and play therapy for children.",
    "phone": "972-721-6555",
    "address": "500 E John Carpenter Fwy, Suite 250, Irving, TX 75062",
    "area": "Irving, TX",
    "hours": "Mon-Thu 8am-8pm; Fri 8am-5pm",
    "hours247": false,
    "free": true,
    "requirements": "Must live, work, attend school in Irving, or be a crime victim there; walk-ins welcome, appointment recommended.",
    "website": "https://www.irvingfac.com"
  },
  {
    "slug": "outreach-denton",
    "name": "OUTreach Denton",
    "category": "lgbtq",
    "description": "Volunteer-run LGBTQ+ nonprofit offering peer support, a teen program, social events, and a curated directory of local/state/national resources.",
    "phone": "940-566-1286",
    "address": "",
    "area": "Denton, TX",
    "hours": "Call for current hours (teen group 2nd/4th Sundays; adult social meetup 3rd Thursday monthly)",
    "hours247": false,
    "free": true,
    "requirements": "None — open to LGBTQ+ community members and allies in the Denton area.",
    "website": "https://outreachdenton.org"
  },
  {
    "slug": "pflag-fort-worth",
    "name": "PFLAG – Fort Worth",
    "category": "lgbtq",
    "description": "Local chapter of the national PFLAG network offering peer support groups, education, and advocacy for LGBTQ+ people and their families.",
    "phone": "817-382-7353",
    "address": "908 Pennsylvania Avenue, Fort Worth, TX 76104",
    "area": "Fort Worth, TX",
    "hours": "Monthly meeting 1st Thursday 6:45pm; social meetup 2nd Wednesday 6pm; trans support group last Sunday monthly via Zoom",
    "hours247": false,
    "free": true,
    "requirements": "None — open to parents, families, allies, and LGBTQ+ individuals.",
    "website": "https://www.pflagfortworth.org"
  },
  {
    "slug": "dallas-hope-charities",
    "name": "Dallas Hope Charities — Dallas Hope Center",
    "category": "lgbtq",
    "description": "Transitional living program for LGBTQ+ young adults (18-24) experiencing homelessness, providing shelter for up to a year plus life-skills training, healthcare access, and job/education support.",
    "phone": "",
    "address": "",
    "area": "Dallas, TX",
    "hours": "Call/email for current hours — intake requires a waitlist application",
    "hours247": false,
    "free": true,
    "requirements": "Application and resident screening required before admission.",
    "website": "https://dallashopecharities.org"
  },
  {
    "slug": "journey-to-dream-kyles-place",
    "name": "Journey to Dream — Kyle's Place",
    "category": "shelter",
    "description": "Denton County's only youth transitional-living campus, providing residential shelter, meals, medical/dental care, case management, mental health counseling, and academic support for homeless/at-risk teens ages 14-19.",
    "phone": "469-470-2382",
    "address": "579 N Valley Parkway, Suite 200, Lewisville, TX 75067",
    "area": "Lewisville, TX",
    "hours": "Call for current hours/referral process",
    "hours247": false,
    "free": true,
    "requirements": "Serves ages 14-19; call for referral/intake process.",
    "website": "https://www.journeytodream.org"
  },
  {
    "slug": "austin-street-sisterhood",
    "name": "Austin Street Center — Sisterhood Program",
    "category": "shelter",
    "description": "Large Dallas homeless shelter with a dedicated women-only 'Sisterhood' program for women who became homeless due to abuse, exploitation, addiction, or mental illness, offering counseling, life-skills training, and workforce development.",
    "phone": "214-428-4242",
    "address": "1717 Jeffries Street, Dallas, TX 75226",
    "area": "Dallas, TX",
    "hours": "General intake Mon-Fri 11am-4pm (beds often fill by noon; lottery used when demand exceeds capacity)",
    "hours247": false,
    "free": false,
    "requirements": "Women 18+ (shelter also serves men 45+ separately); valid government ID required; must be able to self-care; no registered sex offenders. Sisterhood is an internal program for women already in shelter care, not a separate walk-in intake.",
    "website": "https://austinstreet.org",
    "offersDetox": false
  },
  {
    "slug": "center-for-transforming-lives",
    "name": "Center for Transforming Lives",
    "category": "shelter",
    "description": "Fort Worth nonprofit providing emergency shelter, transitional/permanent supportive housing, and rapid re-housing for homeless women — with an emphasis on pregnant women and single mothers — plus childcare, counseling, and economic-mobility services.",
    "phone": "817-332-6191",
    "address": "",
    "area": "Fort Worth, TX",
    "hours": "Call the main line; shelter/rapid re-housing access is coordinated through the Partnership Home coordinated-entry system, not direct walk-in",
    "hours247": false,
    "free": false,
    "requirements": "Serves pregnant women and single mothers experiencing homelessness (one program serves those with children up to age 3); shelter location is not publicly listed.",
    "website": "https://transforminglives.org",
    "offersDetox": false
  },
  {
    "slug": "samaritan-inn",
    "name": "The Samaritan Inn",
    "category": "shelter",
    "description": "Transitional shelter serving men, women, and families in Collin County, with single women housed together while working a structured program toward employment and self-sufficiency.",
    "phone": "972-542-5302",
    "address": "1514 N McDonald St, McKinney, TX 75071",
    "area": "McKinney, TX",
    "hours": "Intake interviews Tue, Thu, Sun 8am-1pm, first-come-first-served",
    "hours247": false,
    "free": true,
    "requirements": "Must be drug- and alcohol-free for 30 days prior to intake; no violent-offense convictions in most cases; must be willing to work; drug test and background check at intake; government ID and Social Security card required. Typical stay 4-6 months.",
    "website": "https://saminn.org",
    "offersDetox": false
  },
  {
    "slug": "arlington-life-shelter",
    "name": "Arlington Life Shelter",
    "category": "shelter",
    "description": "General emergency shelter for single men, single women, and families in Arlington; women and children make up over half the shelter's population.",
    "phone": "817-548-9885",
    "address": "325 W Division Street, Arlington, TX 76011",
    "area": "Arlington, TX",
    "hours": "New-guest intake/check-in Mon-Fri 2pm-4pm; call ext. 3301 to check bed availability before arriving",
    "hours247": false,
    "free": false,
    "requirements": "Two forms of ID (one photo ID); background check; random breathalyzer/drug testing permitted at any time.",
    "website": "https://arlingtonlifeshelter.org",
    "offersDetox": false
  },
  {
    "slug": "cardinal-house-recovery",
    "name": "Cardinal House Recovery",
    "category": "sober-living",
    "description": "Men's sober living homes across Dallas, Richardson, Frisco, and Plano; 12-step-oriented with an emphasis on employment and case management.",
    "phone": "214-897-3092",
    "address": "13853 Peyton Drive, Dallas, TX",
    "area": "Dallas, TX",
    "hours": "Call or email to check availability",
    "hours247": false,
    "free": false,
    "requirements": "18+; must be committed to staying sober, typically after completing detox/residential treatment. Rent $1,000/month ($1,500 at the Plano house) plus a $100 move-in fee.",
    "website": "https://cardinalhouserecovery.com",
    "offersDetox": false
  },
  {
    "slug": "dallas-sober-living-solutions",
    "name": "Dallas Sober Living Solutions",
    "category": "sober-living",
    "description": "Independent-living recovery homes for men and women transitioning out of rehab, with separate houses in North Dallas, Richardson, and Plano.",
    "phone": "469-412-4572",
    "address": "",
    "area": "Dallas, TX",
    "hours": "Call to check availability; admissions decisions generally within 24 hours",
    "hours247": false,
    "free": false,
    "requirements": "Application and government-issued photo ID required; rent ranges $1,000-$1,800/month depending on house.",
    "website": "https://dallassoberliving.com",
    "offersDetox": false
  },
  {
    "slug": "bridges-sober-homes",
    "name": "Bridges Sober Homes",
    "category": "sober-living",
    "description": "Gender-specific sober living homes serving Denton County, with 12-step participation required and a live-in house manager.",
    "phone": "940-233-8700",
    "address": "4251 FM 2181, Corinth, TX 76210",
    "area": "Corinth, TX",
    "hours": "24/7 staffed",
    "hours247": true,
    "free": false,
    "requirements": "12-step program or equivalent required; zero-tolerance policy for use. Call for current rent pricing.",
    "website": "https://bridgessoberhomes.com",
    "offersDetox": false
  },
  {
    "slug": "chapter-house-recovery",
    "name": "Chapter House Recovery",
    "category": "sober-living",
    "description": "Structured transitional sober living for adult men in early recovery in Richardson, paired with the organization's own outpatient (PHP/IOP) clinical program for those who need more support.",
    "phone": "469-991-2181",
    "address": "1771 International Parkway, Suite 129, Richardson, TX 75081",
    "area": "Richardson, TX",
    "hours": "24-hour staff with individualized case managers",
    "hours247": true,
    "free": false,
    "requirements": "Adult men in early recovery, including dual-diagnosis; 5-stage intake process (screening, clinical assessment, fit assessment, financial/insurance, move-in prep). Call for pricing.",
    "website": "https://chapterhouserecovery.com",
    "offersDetox": false
  },
  {
    "slug": "oxford-house-dfw",
    "name": "Oxford House (DFW-area homes)",
    "category": "sober-living",
    "description": "Nationally recognized network (since 1975) of self-run, democratically-operated, single-gender recovery homes, with individual houses across Fort Worth, Denton, Arlington, Dallas, Garland, Irving, and other DFW cities.",
    "phone": "800-689-6411",
    "address": "",
    "area": "DFW metro (multiple cities)",
    "hours": "Find and apply to a specific open house via the official vacancy search at oxfordvacancies.com",
    "hours247": false,
    "free": false,
    "requirements": "Single-gender houses; commonly entered after a rehab or detox stay; current residents interview and vote on new members; no professional staff — peer-run. Equal Expense Share typically $125-$250/week.",
    "website": "https://www.oxfordhouse.org",
    "offersDetox": false
  },
  {
    "slug": "asic-recovery-services",
    "name": "ASIC Recovery Services",
    "category": "sober-living",
    "description": "Men-only sober living in Fort Worth positioned as a bridge between intensive treatment and independent living, paired with the organization's own outpatient (IOP/PHP) treatment services.",
    "phone": "832-681-9643",
    "address": "3256 Lackland Rd, Fort Worth, TX 76116",
    "area": "Fort Worth, TX",
    "hours": "Full-time live-in house manager",
    "hours247": false,
    "free": false,
    "requirements": "Call for admission criteria and pricing — not detailed on their site.",
    "website": "https://asicrecoveryservices.com",
    "offersDetox": false
  },
  {
    "slug": "simply-grace",
    "name": "Simply Grace",
    "category": "sober-living",
    "description": "Women's recovery residence network across Dallas, Plano, Richardson, and Fort Worth, including a 'Mommy and Me' house — one of the few DFW sober-living options letting women in recovery live with their own young children.",
    "phone": "214-774-9808",
    "address": "",
    "area": "Dallas, TX",
    "hours": "Online application, phone interview, and financial agreement, then intake testing",
    "hours247": false,
    "free": false,
    "requirements": "Completed inpatient treatment or currently in an IOP; alcohol/drug-free minimum 7 days. 'Mommy and Me' house accepts up to 2 children ages 2-12. Call for pricing.",
    "website": "https://simplygracehouse.com",
    "offersDetox": false
  },
  {
    "slug": "real-deal-sober-living-womens",
    "name": "Real Deal Sober Living — Women's Homes",
    "category": "sober-living",
    "description": "Women-only sober living homes in Dallas, Richardson, and Farmers Branch, operated by Real Deal Recovery, a Joint Commission-accredited behavioral health company with integrated outpatient treatment; pet-friendly.",
    "phone": "469-747-1201",
    "address": "",
    "area": "Dallas, TX",
    "hours": "Admissions line daily 8am-8pm",
    "hours247": false,
    "free": false,
    "requirements": "No fixed minimum sobriety length — residents can move in after detox, after residential treatment, or when a prior address isn't safe. Rent around $500/month (insurance doesn't cover rent).",
    "website": "https://www.realdealrecovery.com",
    "offersDetox": false
  },
  {
    "slug": "dallas-serenity-ranch",
    "name": "Dallas Serenity Ranch",
    "category": "sober-living",
    "description": "Women-only sober living home on a 5.5-acre gated property in Denton County, with daily breathalyzer testing and a nightly curfew.",
    "phone": "214-794-4100",
    "address": "",
    "area": "Hickory Creek, TX",
    "hours": "Now accepting applications — contact via phone or email",
    "hours247": false,
    "free": false,
    "requirements": "Call to confirm sobriety/detox prerequisites; pricing not published.",
    "website": "https://dallasserenityranch.com",
    "offersDetox": false
  },
  {
    "slug": "the-butterfly-way",
    "name": "The Butterfly Way",
    "category": "sober-living",
    "description": "'Established by women for women' 12-step-based sober living residence in North Dallas, with daily alcohol monitoring and weekly drug screening; medication-assisted-treatment friendly.",
    "phone": "469-998-1922",
    "address": "",
    "area": "Dallas, TX",
    "hours": "Apply online; call or text for details",
    "hours247": false,
    "free": false,
    "requirements": "Call to confirm sobriety/detox prerequisites; pricing not published.",
    "website": "https://thebutterflyway.com",
    "offersDetox": false
  },
  {
    "slug": "fort-behavioral-health",
    "name": "Fort Behavioral Health",
    "category": "recovery",
    "description": "JCAHO-accredited private residential treatment center in Fort Worth with an onsite medically-monitored detox unit explicitly open to people seeking detox on its own, not just as part of a longer program.",
    "phone": "844-332-1807",
    "address": "7140 Oakmont Boulevard, Fort Worth, TX 76132",
    "area": "Fort Worth, TX",
    "hours": "Call for intake hours",
    "hours247": false,
    "free": false,
    "requirements": "Comprehensive assessment required; accepts Aetna, Cigna, BCBS, Humana, UnitedHealthcare, TRICARE, and others.",
    "website": "https://fortbehavioral.com",
    "offersDetox": true
  },
  {
    "slug": "medical-city-green-oaks",
    "name": "Medical City Green Oaks Hospital",
    "category": "recovery",
    "description": "HCA-affiliated Dallas psychiatric hospital with an inpatient addiction unit offering medically supervised alcohol and drug withdrawal management for adults needing 24-hour nursing care.",
    "phone": "972-770-0818",
    "address": "7808 Clodus Fields Dr, Dallas, TX 75251",
    "area": "Dallas, TX",
    "hours": "Call for admission hours",
    "hours247": false,
    "free": false,
    "requirements": "Adults 18+ requiring 24-hour nursing care for withdrawal management; detox is bundled with the inpatient program, not offered as a standalone stay.",
    "website": "https://medicalcityhealthcare.com",
    "offersDetox": true
  },
  {
    "slug": "sante-center-for-healing",
    "name": "Santé Center for Healing",
    "category": "recovery",
    "description": "Private residential addiction treatment campus in Argyle (Denton County) with a dedicated medical detox unit that transitions directly into residential, IOP, or outpatient care.",
    "phone": "866-238-3154",
    "address": "914 Country Club Rd, Argyle, TX 76226",
    "area": "Argyle, TX",
    "hours": "Intake evaluation runs up to 3 days",
    "hours247": false,
    "free": false,
    "requirements": "Multi-day medical/psychological evaluation on intake; detox is bundled with residential care, not offered as a standalone stay. Accepts Aetna, Cigna, and other major plans.",
    "website": "https://santecenter.com",
    "offersDetox": true
  }
]
